Ensure prisma client initialized after wasm engine initialized (#461)
For prisma-client-js generator or cases where there are dynamic import to the prisma wasm modules, we need to make sure we are instantiating the prisma client later in the flow when the wasm would have been initialized.

Fixes regression introduced in #443 that appears when querying in a deployed app

```
ReferenceError: Cannot access 'UL' before initialization
```